#                       __ _                        _
#       ___ ___  _ __  / _(_) __ _  _   _ _ __ ___ | |
#      / __/ _ \|  _ \| |_| |/ _  || | | |  _ ` _ \| |
#     | (_| (_) | | | |  _| | (_| || |_| | | | | | | |
#      \___\___/|_| |_|_| |_|\__, (_)__, |_| |_| |_|_|
#                            |___/  |___/
#
#  Environmental specific configuration for running the acceptance test.
#  The targeted environment can be overridden by passing the TEST_ENV environment
#  variable.
#
#  $ bundle exec cucumber TEST_ENV=test
#

test02:
  :host: https://cc0dbtristeve.cc.nih.gov
test01:
  :host: https://btristestportal.cc.nih.gov
Prod:
  :host: https://btrisportal.cc.nih.gov


#Prod:
#  :host: https://btrisportal.cc.nih.gov
#  :server_name: QPHISSQL01
#  :db_username: phis_app
#  :db_password: 6LGNUuKe
#  :phis_db_name: PHIS_DB_QA31
#  :fsis_db_name: FSISSecurity_QA31

chrome:
  :browser: chrome
firefox:
  :browser: firefox
iexplorer:
  :browser: ie
#slow:
#  :step_delay: true
#fast:
#  :step_delay: false